
export const UserActionTypes = {
    SET_CURRENT_USER: 'SET_CURRENT_USER',
    SET_CURRENT_ACCESS_TOKEN: 'SET_CURRENT_ACCESS_TOKEN',
    SET_CURRENT_REFRESH_TOKEN: 'SET_CURRENT_REFRESH_TOKEN',
    SET_USER_LANGUAGE: 'SET_USER_LANGUAGE',
    SET_CSRF_TOKEN: 'SET_CSRF_TOKEN'
}

